...
env:
  SLACK_WEBHOOK_URL: https://hooks.slack.com/triggers/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
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  smoke-test:
   runs-on: ubuntu-latest
   container:
     image: dannydainton/htmlextra
   steps:
     - name: Cloning Repository
       id: initializing
       uses: actions/checkout@master
     - name: Executing API test suite 
       run: newman run "postman_collection.json" --environment "postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export report.html
     - if: failure()
       uses: actions/upload-artifact@v2
       id: generating-report
       with:
         name: reports
         path: report.html
     - uses: 8398a7/action-slack@v3
       with:
         status: custom
         custom_payload: |
           {
              text: "Test Execution Passed",
              attachments: [{
                  color: 'good',
                  text: `Test Execution for ${process.env.AS_WORKFLOW} workflow has SUCCEEDED! :heavy_check_mark:`,
                  fields: [{
                    title: "Test Type",
                    value: 'Smoke Test',
                    short: false  
                  },
                  {
                    title: "Overall APIs Status",
                    value: "Healthy :heavy_check_mark:",
                    short: false
                  },
                  {
                    title: "Repository",
                    value: `${process.env.AS_REPO}`,
                    short: false  
                  },
                  {
                    title: "Author",
                    value: `${process.env.AS_AUTHOR}`,
                    short: false
                  },
                  {
                    title: "Execution Time",
                    value: `${process.env.AS_TOOK}`,
                    short: false
                  },
                  {
                    title: "Number of Requests",
                    value: '39',
                    short: true 
                  },
                  {
                    title: "Number of Assertions",
                    value: '64',
                    short: true    
                  }]
   
