name: Generate pols

on: push

jobs:
    pandoc:
        runs-on: ubuntu-latest

        steps:
          - name: Check out code
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              
          - uses: docker://pandoc/latex:latest-ubuntu
            with:
              entrypoint: /bin/sh
              args: -c .github/scripts/mkpdf.sh
              
          - name: Upload output
            uses: actions/upload-artifact@master
            with:
              name: figgov-policies.pdf
              path: figgov-policies.pdf
