name: Generate PDFs

on: push

jobs:
    Generating-PDFs:
        runs-on: ubuntu-latest

        steps:
          - name: Check out code
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              
          - uses: docker://pandoc/latex:latest-ubuntu
            with:
              entrypoint: /bin/sh
              args: -c .github/scripts/policies.sh

          - name: Upload output
            uses: actions/upload-artifact@master
            with:
              name: Figma-Policies-Combined.pdf
              path: Figma-Policies-Combined.pdf
              
          - uses: docker://pandoc/latex:latest-ubuntu
            with:
              entrypoint: /bin/sh
              args: >-
                 --template=./.github/templates/template.tex
                 -c .github/scripts/procedures.sh
              
                  
          - name: Upload output
            uses: actions/upload-artifact@master
            with:
              name: Figma-Procedures-Combined.pdf
              path: Figma-Procedures-Combined.pdf
